# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssInfoSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.CharField(max_length=255, null=True, verbose_name='链接')),
                ('feed_title', models.CharField(default='<title>(.*?)</title>', max_length=255, null=True, verbose_name='标题正则')),
                ('connect', models.CharField(max_length=255, null=True, verbose_name='内容正则')),
            ],
            options={
                'verbose_name': 'rss_info_spider',
                'verbose_name_plural': 'rss_info_spider',
            },
        ),
    ]
