# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssinfospider',
            options={'verbose_name': '用户规则', 'verbose_name_plural': '用户规则'},
        ),
        migrations.AlterModelTable(
            name='rssinfospider',
            table='rss_info_spider',
        ),
    ]
