# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-19 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190819_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssinfospider',
            name='xml_name',
            field=models.CharField(max_length=50, null=True, verbose_name='xml文件名'),
        ),
    ]
