# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20190820_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssresultinfo',
            name='xml_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.RssInfoSpider', verbose_name='xml文件'),
        ),
    ]
