# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-20 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20190820_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssresultinfo',
            name='spider_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='爬取时间'),
        ),
    ]
