# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-20 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_rssresultinfo_spider_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssinfospider',
            name='connect_rule',
            field=models.TextField(null=True, verbose_name='内容正则'),
        ),
        migrations.AlterField(
            model_name='rssresultinfo',
            name='spider_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='爬取时间'),
        ),
    ]
