# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-20 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_rssinfospider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssinfospider',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
