# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_rssinfospider_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssinfospider',
            name='next_href_rule',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='下一页正则'),
        ),
    ]
