# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_rssinfospider_next_href_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssresultinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
