# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-07 17:22
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('keep_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('poll_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('browse_num', models.IntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'verbose_name_plural': '文章详情',
                'db_table': 'article',
                'verbose_name': '文章详情',
            },
        ),
        migrations.CreateModel(
            name='ArticleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='分类名')),
            ],
            options={
                'verbose_name_plural': '文章分类',
                'db_table': 'article_class',
                'verbose_name': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '文章标签',
                'db_table': 'article_type',
                'verbose_name': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '评论',
                'db_table': 'comment',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '收藏',
                'db_table': 'keep',
                'verbose_name': '收藏',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '点赞',
                'db_table': 'pool',
                'verbose_name': '点赞',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ArticleClass', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ManyToManyField(to='app.ArticleType', verbose_name='文章标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
