# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-07 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('keep_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('poll_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('browse_num', models.IntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'verbose_name_plural': '文章详情',
                'db_table': 'article',
                'verbose_name': '文章详情',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='标签名')),
            ],
            options={
                'db_table': 'article_type',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
            options={
                'verbose_name_plural': '评论',
                'db_table': 'comment',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '收藏',
                'db_table': 'keep',
                'verbose_name': '收藏',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
            ],
            options={
                'verbose_name_plural': '点赞',
                'db_table': 'pool',
                'verbose_name': '点赞',
            },
        ),
    ]
