# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-12 15:03
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='p', max_length=1, verbose_name='文章状态')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('keep_num', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('poll_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('browse_num', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'verbose_name_plural': '文章详情',
                'db_table': 'article',
                'verbose_name': '文章详情',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='分类名')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
            ],
            options={
                'verbose_name_plural': '文章分类',
                'db_table': 'article_category',
                'verbose_name': '文章分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '文章标签',
                'verbose_name': '文章标签',
                'db_table': 'article_type',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '收藏',
                'verbose_name': '收藏',
                'db_table': 'keep',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
            ],
            options={
                'verbose_name_plural': '点赞',
                'verbose_name': '点赞',
                'db_table': 'pool',
            },
        ),
    ]
