# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-14 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiDuHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=225, verbose_name='关键词')),
                ('href', models.CharField(max_length=225, verbose_name='地址')),
                ('date', models.DateTimeField(default=datetime.datetime.now, max_length=225, verbose_name='日期')),
            ],
            options={
                'db_table': 'baidu_hot',
                'verbose_name': '百度热榜',
                'verbose_name_plural': '百度热榜',
            },
        ),
        migrations.CreateModel(
            name='WeiBoHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=225, verbose_name='关键词')),
                ('href', models.CharField(max_length=225, verbose_name='地址')),
                ('grade', models.CharField(default='无', max_length=225, verbose_name='等级')),
                ('date', models.DateTimeField(default=datetime.datetime.now, max_length=255, verbose_name='日期')),
            ],
            options={
                'db_table': 'weibo_hot',
                'verbose_name': '微博热榜',
                'verbose_name_plural': '微博热榜',
            },
        ),
    ]
